fastparcel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from core import views, consumers

from core.customer import views as customer_views
from core.courier import views as courier_views, apis as courier_apis

customer_urlpatters = [
    path('', customer_views.home, name="home"),
    path('profile/', customer_views.profile_page, name="profile"),
    path('payment_method/', customer_views.payment_method_page, name="payment_method"),
    path('create_job/', customer_views.create_job_page, name="create_job"),

    path('jobs/current/', customer_views.current_jobs_page, name="current_jobs"),
    path('jobs/archived/', customer_views.archived_jobs_page, name="archived_jobs"),
    path('jobs/<job_id>/', customer_views.job_page, name="job"),
]

courier_urlpatters = [
    path('', courier_views.home, name="home"),
    path('jobs/available/', courier_views.available_jobs_page, name="available_jobs"),
    path('jobs/available/<id>/', courier_views.available_job_page, name="available_job"),
    path('jobs/current/', courier_views.current_job_page, name="current_job"),
    path('jobs/current/<id>/take_photo/', courier_views.current_job_take_photo_page, name="current_job_take_photo"),
    path('jobs/complete/', courier_views.job_complete_page, name="job_complete"),
    path('jobs/archived/', courier_views.archived_jobs_page, name="archived_jobs"),
    path('profile/', courier_views.profile_page, name="profile"),
    path('payout_method/', courier_views.payout_method_page, name="payout_method"),

    path('api/jobs/available/', courier_apis.available_jobs_api, name="available_jobs_api"),
    path('api/jobs/current/<id>/update/', courier_apis.current_job_update_api, name="current_job_update_api"),
    path('api/fcm-token/update/', courier_apis.fcm_token_update_api, name="fcm_token_update_api"),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', views.home),

    path('sign-in/', auth_views.LoginView.as_view(template_name="sign_in.html")),
    path('sign-out/', auth_views.LogoutView.as_view(next_page="/")),
    path('sign-up/', views.sign_up),
    
    path('customer/', include((customer_urlpatters, 'customer'))),
    path('courier/', include((courier_urlpatters, 'courier'))),
    path('firebase-messaging-sw.js', (TemplateView.as_view(template_name="firebase-messaging-sw.js", content_type="application/javascript",))),
]

websocket_urlpatterns = [
    path('ws/jobs/<job_id>/', consumers.JobConsumer.as_asgi())
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Customer(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  avatar = models.ImageField(upload_to='customer/avatars/', blank=True, null=True)
  phone_number = models.CharField(max_length=50, blank=True)
  stripe_customer_id = models.CharField(max_length=255, blank=True)
  stripe_payment_method_id = models.CharField(max_length=255, blank=True)
  stripe_card_last4 = models.CharField(max_length=255, blank=True)

  def __str__(self):
    return self.user.get_full_name()

class Courier(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  lat = models.FloatField(default=0)
  lng = models.FloatField(default=0)
  paypal_email = models.EmailField(max_length=255, blank=True)
  fcm_token = models.TextField(blank=True)

  def __str__(self):
    return self.user.get_full_name()

class Category(models.Model):
  slug = models.CharField(max_length=255, unique=True)
  name = models.CharField(max_length=255)

  def __str__(self):
    return self.name

class Job(models.Model):
  SMALL_SIZE = "small"
  MEDIUM_SIZE = "medium"
  LARGE_SIZE = "large"
  SIZES = (
    (SMALL_SIZE, 'Small'),
    (MEDIUM_SIZE, 'Medium'),
    (LARGE_SIZE, 'Large'),
  )

  CREATING_STATUS = 'creating'
  PROCESSING_STATUS = 'processing'
  PICKING_STATUS = 'picking'
  DELIVERING_STATUS = 'delivering'
  COMPLETED_STATUS = 'completed'
  CANCELED_STATUS = 'canceled'
  STATUSES = (
    (CREATING_STATUS, 'Creating'),
    (PROCESSING_STATUS, 'Processing'),
    (PICKING_STATUS, 'Picking'),
    (DELIVERING_STATUS, 'Delivering'),
    (COMPLETED_STATUS, 'Completed'),
    (CANCELED_STATUS, 'Canceled'),
  )

  # Step 1
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
  courier = models.ForeignKey(Courier, on_delete=models.CASCADE, null=True, blank=True)
  name = models.CharField(max_length=255)
  description = models.CharField(max_length=255)
  category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
  size = models.CharField(max_length=20, choices=SIZES, default=MEDIUM_SIZE)
  quantity = models.IntegerField(default=1)
  photo = models.ImageField(upload_to='job/photos/')
  status = models.CharField(max_length=20, choices=STATUSES, default=CREATING_STATUS)
  created_at = models.DateTimeField(default=timezone.now)

  # Step 2
  pickup_address = models.CharField(max_length=255, blank=True)
  pickup_lat = models.FloatField(default=0)
  pickup_lng = models.FloatField(default=0)
  pickup_name = models.CharField(max_length=255, blank=True)
  pickup_phone = models.CharField(max_length=50, blank=True)

  # Step 3
  delivery_address = models.CharField(max_length=255, blank=True)
  delivery_lat = models.FloatField(default=0)
  delivery_lng = models.FloatField(default=0)
  delivery_name = models.CharField(max_length=255, blank=True)
  delivery_phone = models.CharField(max_length=50, blank=True)

  # Step 4
  duration = models.IntegerField(default=0)
  distance = models.FloatField(default=0)
  price = models.FloatField(default=0)

  # Extra info
  pickup_photo = models.ImageField(upload_to='job/pickup_photos/', null=True, blank=True)
  pickedup_at = models.DateTimeField(null=True, blank=True)

  delivery_photo = models.ImageField(upload_to='job/delivery_photos/', null=True, blank=True)
  delivered_at = models.DateTimeField(null=True, blank=True)

  def __str__(self):
    return self.description

class Transaction(models.Model):
  IN_STATUS = "in"
  OUT_STATUS = "out"
  STATUSES = (
    (IN_STATUS, 'In'),
    (OUT_STATUS, 'Out'),
  )

  stripe_payment_intent_id = models.CharField(max_length=255, unique=True)
  job = models.ForeignKey(Job, on_delete=models.CASCADE)
  amount = models.FloatField(default=0)
  status = models.CharField(max_length=20, choices=STATUSES, default=IN_STATUS)
  created_at = models.DateTimeField(default=timezone.now)

  def __str__(self):
    return self.stripe_payment_intent_id

core/courier/forms.py
from django import forms
from core.models import Courier

class PayoutForm(forms.ModelForm):
  class Meta:
    model = Courier
    fields = ('paypal_email',)

core/customer/forms.py
from django import forms
from django.contrib.auth.models import User
from core.models import Customer, Job



class BasicUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name')


class BasicCustomerForm(forms.ModelForm):  
    class Meta:
        model = Customer
        fields = ('avatar',)
class JobCreateStep1Form(forms.ModelForm):
    class Meta:
        model = Job
        fields = ('name','description','category','size','quantity','photo')

class JobCreateStep2Form(forms.ModelForm):
    pickup_address = forms.CharField(required=True)
    pickup_name = forms.CharField(required=True)
    pickup_phone = forms.CharField(required=True)


    class Meta:
        model = Job
        fields = ('pickup_address','pickup_lat','pickup_lng','pickup_name','pickup_phone')

class JobCreateStep3Form(forms.ModelForm):
    delivery_address = forms.CharField(required=True)
    delivery_name = forms.CharField(required=True)
    delivery_phone = forms.CharField(required=True)


    class Meta:
        model = Job
        fields = ('delivery_address','delivery_lat','delivery_lng','delivery_name','delivery_phone')        
                

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=250)
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

def clean_email(self):
    email = self.cleaned_data['email'].lower()
    if User.object.filer(email=email):
        raise ValidationError("This Email is already in use.")
        return email

core/courier/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.conf import settings
from django.contrib import messages

from core.models import *
from core.courier import forms

@login_required(login_url="/sign-in/?next=/courier/")
def home(request):
    return redirect(reverse('courier:available_jobs'))

@login_required(login_url="/sign-in/?next=/courier/")
def available_jobs_page(request):
    return render(request, 'courier/available_jobs.html', {
        "GOOGLE_MAP_API_KEY": settings.GOOGLE_MAP_API_KEY
    })

@login_required(login_url="/sign-in/?next=/courier/")
def available_job_page(request, id):
    job = Job.objects.filter(id=id, status=Job.PROCESSING_STATUS).last()

    if not job:
        return redirect(reverse('courier:available_jobs'))

    if request.method == 'POST':
        job.courier = request.user.courier
        job.status = Job.PICKING_STATUS
        job.save()

        try:
            layer = get_channel_layer()
            async_to_sync(layer.group_send)("job_" + str(job.id), {
                'type': 'job_update',
                'job': {
                    'status': job.get_status_display(),
                }
            })
        except:
            pass

        return redirect(reverse('courier:available_jobs'))

    return render(request, 'courier/available_job.html', {
        "job": job
    })

@login_required(login_url="/sign-in/?next=/courier/")
def current_job_page(request):
    job = Job.objects.filter(
        courier=request.user.courier,
        status__in = [
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).last()

    return render(request, 'courier/current_job.html', {
        "job": job,
        "GOOGLE_MAP_API_KEY": settings.GOOGLE_MAP_API_KEY
    })

@login_required(login_url="/sign-in/?next=/courier/")
def current_job_take_photo_page(request, id):
    job = Job.objects.filter(
        id=id,
        courier=request.user.courier,
        status__in=[
            Job.PICKING_STATUS,
            Job.DELIVERING_STATUS
        ]
    ).last()

    if not job:
        return redirect(reverse('courier:current_job'))

    return render(request, 'courier/current_job_take_photo.html', {
        "job": job
    })

@login_required(login_url="/sign-in/?next=/courier/")
def job_complete_page(request):
    return render(request, 'courier/job_complete.html')

@login_required(login_url="/sign-in/?next=/courier/")
def archived_jobs_page(request):
    jobs = Job.objects.filter(
        courier=request.user.courier,
        status=Job.COMPLETED_STATUS
    )

    return render(request, 'courier/archived_jobs.html', {
        "jobs": jobs
    })

@login_required(login_url="/sign-in/?next=/courier/")
def profile_page(request):
    jobs = Job.objects.filter(
        courier=request.user.courier,
        status=Job.COMPLETED_STATUS
    )

    total_earnings = round(sum(job.price for job in jobs) * 0.8, 2)
    total_jobs = len(jobs)
    total_km = sum(job.distance for job in jobs)

    return render(request, 'courier/profile.html', {
        "total_earnings": total_earnings,
        "total_jobs": total_jobs,
        "total_km": total_km
    })

@login_required(login_url="/sign-in/?next=/courier/")
def payout_method_page(request):
    payout_form = forms.PayoutForm(instance=request.user.courier)

    if request.method == 'POST':
        payout_form = forms.PayoutForm(request.POST, instance=request.user.courier)
        if payout_form.is_valid():
            payout_form.save()

            messages.success(request, "Payout address is updated.")
            return redirect(reverse('courier:profile'))

    return render(request, 'courier/payout_method.html', {
        'payout_form': payout_form
    })

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login

from . import forms

# Create your views here.
def home(request):
    return render(request,'home.html')



def sign_up(request):
    form = forms.SignUpForm()
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email').lower()
            user = form.save(commit=False)
            user.username = email
            user.save()

            

            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/')

    return render(request,'sign_up.html',{'form':form})

core/templates/courier/archived_jobs.html
{% extends 'courier/base.html' %}

{% block head %}
<style>
    small {
        font-size: 12px;
        line-height: 1.2rem;
    }

    .card {
        border-radius: 0;
    }
</style>

{% endblock %}

{% block content %}

<div class="d-flex flex-column h-100" style="padding-bottom: 60px">

    <div class="text-center">
        <div class="btn-group mt-1 mb-1 align-item-center" role="group">
            <a href="{% url 'courier:current_job' %}" class="btn btn-outline-warning">Current Job</a>
            <a href="{% url 'courier:archived_jobs' %}" class="btn btn-warning">Archived Jobs</a>
        </div>
    </div>

    {% if jobs %}

    {% for job in jobs %}
    <div class="card">
        <div class="card-body p-2">
            <div class="media">
                <img src="{{ job.photo.url }}" class="rounded-lg mr-3" width="50px" height="50px">
                <div class="media-body">
                    <b>{{ job.name }}</b>
                    <div class="d-flex">
                        <div class="flex-grow-1 mr-2">

                            <small class="text-success">
                                <i class="fas fa-car"></i> <span>{{ job.distance }}</span> km
                                <i class="far fa-clock ml-2"></i> <span>{{ job.duration }}</span> mins
                            </small>

                            <div class="d-flex align-items-center mt-2">
                                <i class="fas fa-map-marker-alt"></i>
                                <small class="text-secondary ml-2">{{ job.pickup_address }}</small>
                            </div>

                            <div class="d-flex align-items-center mt-2">
                                <i class="fas fa-flag-checkered"></i>
                                <small class="text-secondary ml-2">{{ job.delivery_address }}</small>
                            </div>

                        </div>
                        $<h3>{{ job.price }}</h3>

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    {% else %}

    <div id="main" class="text-center">
        <p>You have no job now. Let's pick a new one.</p>
    </div>

    {% endif %}

</div>

{% include 'courier/bottom_tabs.html' %}

{% endblock %}

core/templates/courier/available_job.html
{% extends 'courier/base.html' %}
{% load static %}

{% block head %}

<style>
    .header {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        height: 60px;
        display: flex;
        align-items: center;
        padding: 0 20px;
        background-color: #FFC106;
        box-shadow: 0 1px 5px rgba(0, 0, 0, 0.2);
    }
</style>

{% endblock %}

{% block content%}

<div class="header">
    <a href="{% url 'courier:available_jobs' %}" class="mr-2">
        <i class="fas fa-chevron-left text-dark"></i>
    </a>
    <h5 class="mt-1 mb-0">Available Jobs</h5>
</div>

<div class="container-fluid" style="padding-top: 80px">
    <div class="media">
        <img src="{{ job.photo.url }}" class="rounded-lg mr-3" width="100" height="100">
        <div class="media-body">
            <h4>{{ job.name }}</h4>
            <span>{{ job.get_size_display }} Size</span><br />
            <span>{{ job.quantity }} Item(s)</span><br />
            <span>${{ job.price }}</span>
        </div>
    </div>
    <hr />

    <div class="d-flex align-items-center text-secondary mb-3">
        <i class="fas fa-map-marker-alt"></i>
        <span class="ml-2">{{ job.pickup_address }}</span>
    </div>

    <div class="d-flex align-items-center text-secondary mb-2">
        <i class="fas fa-flag-checkered"></i>
        <span class="ml-2">{{ job.delivery_address }}</span>
    </div>
    <hr />

    <b class="text-secondary">CUSTOMER</b>
    <div class="media align-items-center mt-2">
        <img src="{% if job.customer.avatar %}{{ job.customer.avatar.url }}{% else %}{% static 'img/avatar.png' %}{% endif %}"
            class="rounded-circle mr-3" width="60" height="60">
        <div class="media-body">
            <h5 class="text-warning">{{ job.customer.user.get_full_name }}</h5>
            <span>{{ job.customer.phone_number }}</span>
        </div>
    </div>
    <hr />

    <form method="POST">
        {% csrf_token %}
        <button class="btn btn-warning btn-block">Accept This Job</button>
    </form>

</div>

{% endblock %}

core/templates/courier/available_jobs.html
{% extends 'courier/base.html' %}

{% block head %}
<script
    src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAP_API_KEY }}&callback=initMap&libraries=places&v=weekly"
    defer></script>

<script>
    function initMap() {
        const map = new google.maps.Map(document.getElementById("map"), {
            zoom: 13,
            center: { lat: 57.704618389854026, lng: 11.96531267255364 },
        });

        // Get available jobs via API
        fetch("{% url 'courier:available_jobs_api' %}")
            .then(response => response.json())
            .then(json => {
                // console.log(json);

                // Create a new viewpoint bound
                var bounds = new google.maps.LatLngBounds();

                for (let i = 0; i < json.jobs.length; i++) {
                    const job = json.jobs[i];
                    const position = { lat: job.pickup_lat, lng: job.pickup_lng };
                    const marker = new google.maps.Marker({
                        position,
                        map,
                    });

                    // Increase the bounds to take this point
                    bounds.extend(position);

                    new google.maps.InfoWindow({
                        content: "<small><b>" + job.name + "</b></small><br/><small>" + job.distance + " Km</small>"
                    }).open(map, marker);

                    // Click event for each job
                    marker.addListener("click", () => {
                        showJobDetails(job);
                    });

                    // Fit these bounds to the map
                    map.fitBounds(bounds);
                }
            })
    }

    function showJobDetails(job) {
        $("#job-details").css("display", "block");
        $("#job-name").html(job.name);

        $("#job-photo").attr('src', "/media/" + job.photo);
        $("#pickup-address").html(job.pickup_address);
        $("#delivery-address").html(job.delivery_address);
        $("#duration").html(job.duration);
        $("#distance").html(job.distance);
        $("#price").html(job.price);

        $("#job-details").on("click", function () {
            window.location.href = "/courier/jobs/available/" + job.id + "/";
        })

    }

    messaging.onMessage((payload) => {
        window.location.reload();
    })
</script>

<style>
    .gm-ui-hover-effect {
        display: none !important;
    }

    #map {
        flex: 1;
    }

    small {
        font-size: 12px;
        line-height: 1.2rem;
    }

    .card {
        border: none;
    }

    #job-details {
        display: none;
    }
</style>

{% endblock %}

{% block content %}

<div class="d-flex flex-column h-100" style="padding-bottom: 60px">
    <div id="map"></div>

    <div id="job-details" class="card">
        <div class="card-body p-2">
            <div class="media">
                <img id="job-photo" class="rounded-lg mr-3" width="50px" height="50px">
                <div class="media-body">
                    <b id="job-name"></b>
                    <div class="d-flex">
                        <div class="flex-grow-1 mr-2">

                            <small class="text-success">
                                <i class="fas fa-car"></i> <span id="distance"></span> km
                                <i class="far fa-clock ml-2"></i> <span id="duration"></span> mins
                            </small>

                            <div class="d-flex align-items-center mt-2">
                                <i class="fas fa-map-marker-alt"></i>
                                <small id="pickup-address" class="text-secondary ml-2"></small>
                            </div>

                            <div class="d-flex align-items-center mt-2">
                                <i class="fas fa-flag-checkered"></i>
                                <small id="delivery-address" class="text-secondary ml-2"></small>
                            </div>

                        </div>
                        $<h3 id="price"></h3>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'courier/bottom_tabs.html' %}

{% endblock %}

core/templates/courier/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Courier | FastParcel</title>
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/logo.png' %}">
    <link rel="manifest" href="{% static 'manifest.json' %}">

    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {% include 'load_firebase.html' %}

    <script>
        const messaging = firebase.messaging();
        messaging
            .getToken({
                validKey: "BPdEY4HDppswRg54ICf-DTvlH4WzmhTcHSCZ-KWNnl0ZTpsAwnwlnZ4Pyd4NMinNcjE0uRe6LSUN8mYiVWvxNRc"
            })
            .then((currentToken) => {
                console.log(currentToken);
                if (currentToken) {
                    fetch('{% url "courier:fcm_token_update_api" %}?fcm_token=' + currentToken);
                }
            })
            .catch((err) => {
                console.log('An error occured while retrieving token. ', err);
            })
    </script>

    <script>
        let vh = window.innerHeight * 0.01;
        document.documentElement.style.setProperty('--vh', `${vh}px`);
    </script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">

    <style>
        #content {
            height: calc(var(--vh, 1vh) * 100);
        }
    </style>

    {% block head %}{% endblock %}
</head>

<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <script src="https://unpkg.com/bootoast@1.0.1/dist/bootoast.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/bootoast@1.0.1/dist/bootoast.min.css">

    <script>
        function toast(message, type) {
            bootoast.toast({
                position: 'centerBottom',
                message,
                type,
            });
        }

        {% if messages %}

        {% for message in messages %}
        toast('{{ message }}', '{{ message.tags }}');
        {% endfor %}

        {% endif %}
    </script>
</body>

</html>

core/templates/courier/bottom_tabs.html
<style>
    .bottom-tabs {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        height: 60px;
        display: flex;
        background-color: white;
        box-shadow: 0 1px 5px rgba(0, 0, 0, 0.2);
        text-align: center;
    }

    .bottom-tabs>a {
        flex: 1;
        padding: 5px;
        color: #BFBFBF;
        text-decoration: none;
    }

    .bottom-tabs>a>span {
        font-size: 13px;
        font-weight: bold;
        display: block;
    }

    .bottom-tabs>a>i {
        font-size: 20px;
    }

    .bottom-tabs>a.active {
        color: #FFC106;
    }
</style>

{% url 'courier:available_jobs' as available_jobs_url %}
{% url 'courier:current_job' as current_job_url %}
{% url 'courier:archived_jobs' as archived_jobs_url %}
{% url 'courier:profile' as profile_url %}

<div class="bottom-tabs d-flex">
    <a href="{% url 'courier:available_jobs' %}" class="{% if request.path == available_jobs_url %}active{% endif %}">
        <i class="fas fa-map-marked-alt"></i>
        <span>Available Jobs</span>
    </a>
    <a href="{% url 'courier:current_job' %}"
        class="{% if request.path == current_job_url or request.path == archived_jobs_url %}active{% endif %}">
        <i class="fas fa-archive"></i>
        <span>My Jobs</span>
    </a>
    <a href="{% url 'courier:profile' %}" class="{% if request.path == profile_url %}active{% endif %}">
        <i class="fas fa-user"></i>
        <span>Profile</span>
    </a>
</div>

core/templates/courier/current_job_take_photo.html
{% extends 'courier/base.html' %}
{% load static %}

{% block head %}
<script src="{% static 'js/webcam-easy.min.js' %}"></script>
<style>
    body {
        background-color: black;
    }

    .btn-back {
        position: fixed;
        top: 30px;
        left: 30px;
    }

    .buttons {
        position: fixed;
        bottom: 20px;
        left: 0;
        right: 0;
        text-align: center;
    }

    #take-photo-step {
        height: 100%;
        display: flex;
        align-items: center;
    }

    video {
        width: 100%;
        height: auto;
    }

    #upload-step {
        height: 100%;
        display: none;
        align-items: center;
    }
</style>

{% endblock %}

{% block content %}

<div id="upload-step">
    <img id="photo">
    <div class="buttons">
        <a id="retake-button" class="btn btn-light" href="javascript:void(retake_photo())">Retake</a>
        <a id="upload-button" class="btn btn-warning" href="javascript:void(upload_photo())">
            Upload {% if job.status == 'picking' %}Pickup{% else %}Drop-off{% endif %} Photo
        </a>
    </div>
</div>

<div id="take-photo-step">
    <video id="webcam" autoplay playsinline></video>
    <canvas id="canvas" class="d-none"></canvas>

    <a href="{% url 'courier:current_job' %}" class="btn-back">
        <i class="fas fa-chevron-left text-light"></i>
    </a>

    <div class="buttons">
        <a href="javascript:void(take_photo())" class="btn btn-warning">
            Take {% if job.status == 'picking' %}Pickup{% else %}Drop-off{% endif %} Photo
        </a>
    </div>
</div>

<script>
    const webcamElement = document.getElementById('webcam');
    const canvasElement = document.getElementById('canvas');
    const webcam = new Webcam(webcamElement, 'environment', canvasElement);
    webcam.start();

    function take_photo() {
        let picture = webcam.snap();
        console.log(picture);

        $("#photo").attr("src", picture);
        $("#take-photo-step").css("display", "none");
        $("#upload-step").css("display", "flex");
    }

    function retake_photo() {
        $("#upload-step").css("display", "none");
        $("#take-photo-step").css("display", "flex");
    }

    function upload_photo() {
        document.getElementById("canvas").toBlob(function (blob) {
            var formData = new FormData();
            var upload_name = "{% if job.status == 'picking' %}pickup{% else %}delivery{% endif %}_photo"
            formData.append(upload_name, blob, upload_name + '.png');

            fetch("{% url 'courier:current_job_update_api' job.id %}", {
                method: "POST",
                body: formData
            })
                .then(function (response) { return response.json() })
                .then(function (json) {
                    if (json.success) {
                        window.location.href = "{% if job.status == 'picking' %}{% url 'courier:current_job' %}{% else %}{% url 'courier:job_complete' %}{% endif%}"
                    }
                })
        })
    }

</script>

{% endblock %}

core/templates/courier/job_complete.html
{% extends 'courier/base.html' %}
{% load static %}

{% block content %}
<div class="h-100 d-flex flex-column align-items-center justify-content-center">
    <img src="{% static 'img/complete.gif' %}" class="mb-3" width="200" height="200">
    <p>Your job was completed! Well done.</p>

    <a href="{% url 'courier:home' %}" class="btn btn-warning">Check available jobs</a>
</div>
{% endblock %}

core/templates/courier/payout_method.html
{% extends 'courier/base.html' %}
{% load bootstrap4 %}

{% block head %}
<style>
    .header {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        height: 60px;
        display: flex;
        align-items: center;
        padding: 0 20px;
        background-color: #FFC106;
        box-shadow: 0 1px 5px rgba(0, 0, 0, 0.2);
    }
</style>
{% endblock %}

{% block content %}
<div class="header">
    <a href="{% url 'courier:profile' %}" class="mr-2">
        <i class="fas fa-chevron-left text-dark"></i>
    </a>
    <h5 class="mt-1 mb-0">Profile</h5>
</div>

<div class="container-fluid" style="padding-top: 80px">
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form payout_form %}
        <button type="submit" class="btn btn-block btn-warning">Save</button>
    </form>
</div>

{% endblock %}